### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by FujishigeTemma** [CTFBox/CTFBox#4]

**Comment by kitakou0313** [comment]
- userテーブル
-- ID(自動追加), username, 認証情報 、得点

- questionテーブル
-- ID, タイトル、得点、問題コンテンツ、flag文字列

- 解答状況テーブル
-- ID, userID(userテーブルの外部キー),quesitonID（questionテーブルへの外部キー）、解答状況（boolなど）

**Comment by kitakou0313** [comment]
created, updated, deleted を各テーブルに
